setwd("C:/Users/sfoerster/ABinteractions/Figures")
library(gplots)
pdf("kappa.pdf")
data <- read.table("parameter_comparison.txt",header=T)
subdata <- subset(data,data$parameter=="kappa")
# height <- matrix(subdata$estimate, ncol = 3)
 lower <- matrix(subdata$ci.lb, ncol = 4,byrow=T)
 upper <- matrix(subdata$ci.ub, ncol = 4,byrow=T)
 bars <- matrix(subdata$group, ncol = 2)
 height <- matrix(subdata$estimate, ncol = 4,byrow=T)
 #labels <- matrix(subdata$experiment, ncol = 2)

#barplot2(c(subdata$estimate), plot.ci=TRUE, ci.l=lower, ci.u=upper,names.arg=c("hallo"),col="blue")
mp<-barplot2(height,plot.ci=TRUE,plot.grid = TRUE,col=c("lightblue","mistyrose"), legend = c(bars[1,1],bars[1,2]), ylim=c(0,6),xlab="Antibiotic",cex.lab=1.2,ylab=substitute(paste("Slope ",kappa)),ci.l=lower, ci.u=upper,beside=TRUE)
#mtext(side = 1, substitute(paste("slope ",kappa," [AU]",sep="",collapse=NULL)))
labels <- matrix(subdata$experiment, ncol = 4, byrow = TRUE)
mtext(side = 1, at = colMeans(mp), text = labels[1,], line = 1)
# names(counts)<-c("F89","WHOA")
# counts<-as.matrix(counts)
# barplot(counts, main="kappa",
#         xlab="Number of Gears", col=c("darkblue","green"),
#         legend = colnames(counts), beside=TRUE)
dev.off()

setwd("C:/Users/sfoerster/ABinteractions/Figures")
library(gplots)
pdf("lower.pdf")
data <- read.table("parameter_comparison.txt",header=T)
subdata <- subset(data,data$parameter=="lower")
# height <- matrix(subdata$estimate, ncol = 3)
 lower <- matrix(subdata$ci.lb, ncol = 4,byrow=T)
 upper <- matrix(subdata$ci.ub, ncol = 4,byrow=T)
 bars <- matrix(subdata$group, ncol = 2)
 height <- matrix(subdata$estimate, ncol = 4,byrow=T)
 labels <- matrix(subdata$experiment, ncol = 4)

#barplot2(c(subdata$estimate), plot.ci=TRUE, ci.l=lower, ci.u=upper,names.arg=c("hallo"),col="blue")
mp<-barplot2(height,plot.ci=TRUE,plot.grid = TRUE,col=c("lightblue","mistyrose"), legend = c(bars[1,1],bars[1,2]), ylim=c(0,-5),xlab="Antibiotic",cex.lab=1.2,ylab="growth rate at highest conc.",ci.l=lower, ci.u=upper,beside=TRUE)
#mtext(side = 1, substitute(paste("slope ",kappa," [AU]",sep="",collapse=NULL)))
labels <- matrix(subdata$experiment, ncol = 4, byrow = TRUE)
mtext(side = 1, at = colMeans(mp), text = labels[1,], line = 1)
# names(counts)<-c("F89","WHOA")
# counts<-as.matrix(counts)
# barplot(counts, main="kappa",
#         xlab="Number of Gears", col=c("darkblue","green"),
#         legend = colnames(counts), beside=TRUE)
dev.off()

setwd("C:/Users/sfoerster/ABinteractions/Figures")
library(gplots)
pdf("upper.pdf")
data <- read.table("parameter_comparison.txt",header=T)
subdata <- subset(data,data$parameter=="upper")
# height <- matrix(subdata$estimate, ncol = 3)
 lower <- matrix(subdata$ci.lb, ncol = 4,byrow=T)
 upper <- matrix(subdata$ci.ub, ncol = 4,byrow=T)
 bars <- matrix(subdata$group, ncol = 2)
 height <- matrix(subdata$estimate, ncol = 4,byrow=T)
 labels <- matrix(subdata$experiment, ncol = 4)

#barplot2(c(subdata$estimate), plot.ci=TRUE, ci.l=lower, ci.u=upper,names.arg=c("hallo"),col="blue")
mp<-barplot2(height,plot.ci=TRUE,plot.grid = TRUE,col=c("lightblue","mistyrose"), legend = c(bars[1,1],bars[1,2]), ylim=c(0,3),xlab="Antibiotic",cex.lab=1.2,ylab="growth rate of untreated control",ci.l=lower, ci.u=upper,beside=TRUE)
#mtext(side = 1, substitute(paste("slope ",kappa," [AU]",sep="",collapse=NULL)))
labels <- matrix(subdata$experiment, ncol = 4, byrow = TRUE)
mtext(side = 1, at = colMeans(mp), text = labels[1,], line = 1)
# names(counts)<-c("F89","WHOA")
# counts<-as.matrix(counts)
# barplot(counts, main="kappa",
#         xlab="Number of Gears", col=c("darkblue","green"),
#         legend = colnames(counts), beside=TRUE)
dev.off()

setwd("C:/Users/sfoerster/ABinteractions/Figures")
library(gplots)
pdf("zMIC.pdf")
data <- read.table("parameter_comparison.txt",header=T)
subdata <- subset(data,data$parameter=="zMIC")
# height <- matrix(subdata$estimate, ncol = 3)
 lower <- matrix(subdata$ci.lb, ncol = 4,byrow=T)
 upper <- matrix(subdata$ci.ub, ncol = 4,byrow=T)
 bars <- matrix(subdata$group, ncol = 2)
 height <- matrix(subdata$estimate, ncol = 4,byrow=T)
 labels <- matrix(subdata$experiment, ncol = 4)

#barplot2(c(subdata$estimate), plot.ci=TRUE, ci.l=lower, ci.u=upper,names.arg=c("hallo"),col="blue")
mp<-barplot2(height,plot.ci=TRUE,plot.grid = TRUE,col=c("lightblue","mistyrose"), legend = c(bars[1,1],bars[1,2]), ylim=c(0,1),xlab="Antibiotic",cex.lab=1.2,ylab="zMIC (1=Etest MIC)",ci.l=lower, ci.u=upper,beside=TRUE)
#mtext(side = 1, substitute(paste("slope ",kappa," [AU]",sep="",collapse=NULL)))
labels <- matrix(subdata$experiment, ncol = 4, byrow = TRUE)
mtext(side = 1, at = colMeans(mp), text = labels[1,], line = 1)
# names(counts)<-c("F89","WHOA")
# counts<-as.matrix(counts)
# barplot(counts, main="kappa",
#         xlab="Number of Gears", col=c("darkblue","green"),
#         legend = colnames(counts), beside=TRUE)
dev.off()

setwd("C:/Users/sfoerster/ABinteractions/Figures")
library(gplots)
pdf("inflection.pdf")
data <- read.table("parameter_comparison.txt",header=T)
subdata <- subset(data,data$parameter=="inflection")
subdata <- subset(subdata,subdata$group=="F89")

# height <- matrix(subdata$estimate, ncol = 3)
 lower <- matrix(subdata$ci.lb, ncol = 4,byrow=T)
 upper <- matrix(subdata$ci.ub, ncol = 4,byrow=T)
 bars <- matrix(subdata$group, ncol = 2)
 height <- matrix(subdata$estimate, ncol = 4,byrow=T)
 labels <- matrix(subdata$experiment, ncol = 4)

#barplot2(c(subdata$estimate), plot.ci=TRUE, ci.l=lower, ci.u=upper,names.arg=c("hallo"),col="blue")
mp<-barplot2(height,plot.ci=TRUE,plot.grid = TRUE,col=c("lightblue","mistyrose"), legend = c(bars[1,1],bars[1,2]), ylim=c(0,2),xlab="Antibiotic",cex.lab=1.2,ylab="EC50",ci.l=lower, ci.u=upper,beside=TRUE,log="y")
#mtext(side = 1, substitute(paste("slope ",kappa," [AU]",sep="",collapse=NULL)))
labels <- matrix(subdata$experiment, ncol = 4, byrow = TRUE)
mtext(side = 1, at = colMeans(mp), text = labels[1,], line = 1)
# names(counts)<-c("F89","WHOA")
# counts<-as.matrix(counts)
# barplot(counts, main="kappa",
#         xlab="Number of Gears", col=c("darkblue","green"),
#         legend = colnames(counts), beside=TRUE)
dev.off()

